# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sentence.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "Position" do
    optional :fromPos, :int32, 1
    optional :toPos, :int32, 2
  end
  add_message "Params" do
    optional :sum_weight, :double, 1
    optional :avg_wight, :double, 2
    optional :max_wight, :double, 3
    optional :word_count, :int32, 4
  end
  add_message "Context" do
    optional :size, :int32, 1
    optional :left, :string, 2
    optional :right, :string, 3
  end
  add_message "Concept" do
    optional :link, :string, 1
    optional :hits, :int32, 2
    optional :avgScore, :double, 3
    optional :maxScore, :double, 4
    optional :minScore, :double, 5
    optional :avgNorm, :double, 6
    optional :avgSoftMax, :double, 7
  end
  add_message "Mention" do
    optional :id, :int32, 1
    optional :resolver, :string, 2
    optional :text, :string, 3
    optional :position, :message, 4, "Position"
    optional :params, :message, 5, "Params"
    optional :context, :message, 6, "Context"
    repeated :concepts, :message, 7, "Concept"
  end
  add_message "Token" do
    optional :token, :string, 1
    optional :lemma, :string, 2
    optional :pos_tag, :string, 3
    optional :parserTag, :string, 4
    optional :group, :int32, 5
    repeated :mentions, :int32, 6
  end
  add_message "Sentente" do
    optional :sent, :string, 1
    repeated :mentions, :message, 2, "Mention"
    optional :parser_name, :string, 3
    repeated :parse_result, :message, 4, "Token"
    optional :prevSentence, :string, 5
    optional :nextSentence, :string, 6
  end
end

Position = Google::Protobuf::DescriptorPool.generated_pool.lookup("Position").msgclass
Params = Google::Protobuf::DescriptorPool.generated_pool.lookup("Params").msgclass
Context = Google::Protobuf::DescriptorPool.generated_pool.lookup("Context").msgclass
Concept = Google::Protobuf::DescriptorPool.generated_pool.lookup("Concept").msgclass
Mention = Google::Protobuf::DescriptorPool.generated_pool.lookup("Mention").msgclass
Token = Google::Protobuf::DescriptorPool.generated_pool.lookup("Token").msgclass
Sentente = Google::Protobuf::DescriptorPool.generated_pool.lookup("Sentente").msgclass
