version: '2'

services:
  elastic:
    image: elasticsearch
    command: elasticsearch -Dlog4j.configurationFile=
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - ./data/elastic:/usr/share/elasticsearch/config
    networks:
      - sknn_net

networks:
  sknn_net:

